package commlib.cinvesframework.belief;

public enum BeliefType {

    AREAS,
    BUILDINGS,
    BUILDINGS_ON_FIRE,
    ROADS,
    REFUGE,
    TARGET_LOCATION,
    GOAL_PATH,
    REPAIR_DISTANCE,
    VOLUNTEER,
    CHANGED_ENVIRONMENT,
    REPORTED_BLOCKADES,
    REPORTED_FIRES,
    QUADRANT,
    BUILDINGS_IN_QUADRANT,
    IM_LEADER,
    POLICE_CENTRE
    ;

}
